// Data loader for mapping_presets.json.
//
// Strategy:
//   1. Static import the JSON. Vite resolves the relative path at build time
//      and bundles the file. Works for both `npm run dev` and `npm run build`.
//   2. If the import fails (e.g. data file missing in CI / fresh checkout),
//      fall back to 20 hardcoded placeholder sections so the UI still renders.
//
// Path math:
//   This file: src/ui/src/data/mappings.ts
//   Target:    <project>/data/processed/validation/mapping_presets.json
//   Rel:       ../../data/mapping_presets.json

import type { Mapping, MappingPresets, Pass } from "../types";

import presetsRaw from "../../data/mapping_presets.json";

function asMappingPresets(raw: unknown): MappingPresets {
  // Cast through unknown — the JSON is generated by our own mapper script and
  // already conforms to the schema. Trust the source, but keep the boundary
  // explicit so TS catches downstream changes to types.ts.
  return raw as unknown as MappingPresets;
}

function placeholderMappings(): Mapping[] {
  const placeholders: Array<{ id: string; title: string; pass: Pass }> = [
    { id: "C.1.1.5", title: "Siding PVC", pass: "high" },
    { id: "C.1.2.2", title: "Yeso cartón 10mm", pass: "high" },
    { id: "C.1.3.3", title: "Yeso cartón RH", pass: "medium" },
    { id: "C.2.1", title: "Poliestireno Expandido", pass: "medium" },
    { id: "C.3.2.2", title: "Fe Galvanizado 2do Piso", pass: "review" },
    { id: "C.3.3.1", title: "Yeso cartón", pass: "medium" },
    { id: "C.3.4.2", title: "Yeso cartón (RH)", pass: "medium" },
    { id: "C.4.3", title: "Lana de vidrio", pass: "review" },
    { id: "C.5.1", title: "Cerámica", pass: "medium" },
    { id: "C.7.1", title: "Escalera Interior", pass: "canonical" },
    { id: "C.8.1.1", title: "Madera", pass: "medium" },
    { id: "C.8.2.4", title: "Fibrocemento", pass: "high" },
    { id: "C.8.4", title: "Tapacán", pass: "high" },
    { id: "C.9.2.1", title: "Puerta ancho 70", pass: "high" },
    { id: "C.9.2.2", title: "Puerta ancho 75 con vidrio", pass: "high" },
    { id: "C.9.3.2", title: "Puerta ancho 85", pass: "high" },
    { id: "C.9.4.2", title: "Baño", pass: "review" },
    { id: "C.9.5.2", title: "PVC", pass: "high" },
    { id: "C.10.1", title: "Guardapolvo", pass: "review" },
    { id: "C.11.1.1", title: "Oleo Semibrillo", pass: "review" },
  ];
  return placeholders.map((p) => ({
    section_id: p.id,
    section_title: p.title,
    unit: null,
    status: p.pass === "review" ? "review" : "mapped",
    results: [
      {
        ifc_class: "IfcUnknown",
        conf:
          p.pass === "canonical"
            ? 0.95
            : p.pass === "high"
              ? 0.85
              : p.pass === "medium"
                ? 0.7
                : 0.5,
        rationale:
          "Placeholder — mapping_presets.json not found at build time.",
        filter: {
          c: "AND",
          g: [{ c: "AND", r: [{ p: "ifc_class", op: "equals", v: "IfcUnknown" }] }],
        },
        pass: p.pass,
      },
    ],
  }));
}

export interface LoadedMappings {
  mappings: Mapping[];
  source: "presets" | "placeholder";
  run: MappingPresets["run"] | null;
}

export function loadMappings(): LoadedMappings {
  try {
    const data = asMappingPresets(presetsRaw);
    if (data && Array.isArray(data.mappings) && data.mappings.length > 0) {
      return { mappings: data.mappings, source: "presets", run: data.run };
    }
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn(
      "[mappings] Failed to load mapping_presets.json, using placeholders:",
      err,
    );
  }
  return { mappings: placeholderMappings(), source: "placeholder", run: null };
}